website/views.py
from flask import Blueprint, render_template, request, flash, current_app, redirect, url_for
from flask_login import login_required, current_user
from flask_security import roles_required
from werkzeug.utils import secure_filename
from datetime import datetime, date

import os

from . import db
from .models import Post, Trick, TrickVariant, User, Role, roles_users, UsersTricks, UserData, slugify, Category, DictionaryPhrase

views = Blueprint("views", __name__)


@views.context_processor
def inject_menu_items():
    trick_post = Post.query.filter(Post.category_id == 2).first()
    trick_category = Category.query.filter(Category.id == 2).first()

    about_post = Post.query.filter(Post.category_id == 3).first()
    about_category = Category.query.filter(Category.id == 3).first()
    return dict(menu_trick_post=trick_post, menu_trick_category=trick_category,
                menu_about_post=about_post, menu_about_category=about_category)


# @views.route("/")
# def intro():
#     return render_template("intro.html", user=current_user)


@views.errorhandler(404)
def not_found(e):
    return render_template('404.html', user=current_user)


@views.route('/')
def home():
    return render_template("home.html", user=current_user)


@views.route("/about")
def about():
    post = Post.query.filter(Post.category_id == 3).first()
    posts = Post.query.filter(Post.category_id == 3).all()
    category = Category.query.filter(Category.id == 3).first()
    return render_template('posts/post.html', post=post, posts=posts, user=current_user, category=category.name)


@views.route('/profile')
@login_required
def profile():
    u_tricks = db.session.query(UsersTricks).join(Trick).join(TrickVariant).\
        filter(UsersTricks.user_id == current_user.id).order_by(UsersTricks.created_at.desc())
    user_data = UserData.query.filter(UserData.user_id == current_user.id).first()

    # passing object to template in order to create link using url_for
    add_trick_link = Trick.query.first()

    return render_template('user/profile.html', user=current_user, tricks=u_tricks, user_data=user_data,
                           trick=add_trick_link)


@views.route('/trick/<trick_slug>')
@login_required
def my_trick(trick_slug):
    trick = Trick.query.filter(Trick.slug == trick_slug).first()
    tricks = Trick.query.all()

    # Trick variants that already been done by the current user - query result in tuples
    completed_variants = db.session.query(UsersTricks.trick_variant_id).filter_by(trick_id=trick.id,
                                                                                  user_id=current_user.id).all()
    # Tuple to int conversion
    user_variants = [int(t[0]) for t in completed_variants]

    trick_article = Post.query.filter(Post.slug == trick_slug).first()
    if trick_article:
        article = True
    else:
        article = False

    variants = TrickVariant.query.all()

    return render_template('my_tricks.html', trick=trick, tricks=tricks,
                           user=current_user, all_variants=variants, user_variants=user_variants, article=article)


def add_points(counter, trick_value):
    scale = {0: 1, 1: 1.20, 2: 2, 3: 5}
    if scale[counter]:
        points = scale[counter] * trick_value
        user_data = UserData.query.filter(UserData.user_id == current_user.id).first()
        user_data.skill_points += points
        db.session.add(user_data)
        db.session.commit()


def subtract_points(counter, trick_value):
    scale = {1: 1, 2: 1.20, 3: 2, 4: 5}
    if scale[counter]:
        points = scale[counter] * trick_value
        user_data = UserData.query.filter(UserData.user_id == current_user.id).first()
        user_data.skill_points -= points
        db.session.add(user_data)
        db.session.commit()


@views.route('/add-trick/<trick_slug>/<variant_slug>', methods=['GET', 'POST'])
@login_required
def add_trick(trick_slug, variant_slug):
    trick = Trick.query.filter(Trick.slug == trick_slug).first()
    variant = TrickVariant.query.filter(TrickVariant.slug == variant_slug).first()
    trick_check = UsersTricks.query.filter(UsersTricks.trick_id == trick.id,
                                           UsersTricks.trick_variant_id == variant.id,
                                           UsersTricks.user_id == current_user.id).all()
    variant_count = len(UsersTricks.query.filter(UsersTricks.trick_id == trick.id,
                                                 UsersTricks.user_id == current_user.id).all())
    default_date = date.today().isoformat()
    if not trick_check:
        if request.method == 'POST':
            note = request.form.get("note")
            set_date = request.form.get("date")
            new_date = datetime.fromisoformat(set_date)
            add_points(variant_count, trick.value)
            # if not file_name: FOR IMAGE OR VIDEO
            #     flash('Please fill in all the fields.', category='error')
            new_trick = UsersTricks(trick_id=trick.id, trick_variant_id=variant.id, user_id=current_user.id,
                                    content=note, created_at=new_date)
            db.session.add(new_trick)
            db.session.commit()
            flash('Gratulacje! Dodałeś nowy trick.', category='success')
            return redirect(url_for('views.my_trick', trick_slug=trick_slug))
    else:
        flash('Dodałeś już taki trick', category='error')
        return redirect(url_for('views.my_trick', trick_slug=trick_slug))

    return render_template('tricks/create_users_tricks.html', trick=trick, variant=variant, date=default_date,
                           user=current_user)


# @views.route('/trick-archive/<trick_slug>/<variant_slug>')
# @login_required
# def trick_archive(trick_slug, variant_slug):
#     trick = Trick.query.filter(Trick.slug == trick_slug).first()
#     variant = TrickVariant.query.filter(TrickVariant.slug == variant_slug).first()
#     trick_check = UsersTricks.query.filter(UsersTricks.trick_id == trick.id,
#                                            UsersTricks.trick_variant_id == variant.id,
#                                            UsersTricks.user_id == current_user.id).first_or_404()
#     return render_template('tricks/trick_archive.html', trick=trick, variant=variant, info=trick_check,
#                            user=current_user)


@views.route('/edit-trick/<trick_slug>/<variant_slug>', methods=['GET', 'POST'])
@login_required
def user_edit_trick(trick_slug, variant_slug):
    trick = Trick.query.filter(Trick.slug == trick_slug).first()
    variant = TrickVariant.query.filter(TrickVariant.slug == variant_slug).first()
    trick_check = UsersTricks.query.filter(UsersTricks.trick_id == trick.id,
                                           UsersTricks.trick_variant_id == variant.id,
                                           UsersTricks.user_id == current_user.id).first()
    if trick_check:
        if request.method == 'POST':
            note = request.form.get("note")
            date = request.form.get("date")
            trick_check.content = note
            if date:
                new_date = datetime.fromisoformat(date)
                trick_check.created_at = new_date
            db.session.add(trick_check)
            db.session.commit()
            flash('Zmiany zostały zapisane', category='success')
            return redirect(url_for('views.profile'))
    else:
        flash("Nie dodałeś jeszcze takiego tricku", category='error')
        return redirect(url_for('views.my_trick', trick_slug=trick_slug))
    return render_template('tricks/edit_trick.html', trick=trick, variant=variant, info=trick_check,
                           user=current_user)


@views.route('/delete-trick/<trick_slug>/<variant_slug>', methods=['GET', 'POST'])
@login_required
def delete_user_trick(trick_slug, variant_slug):
    trick = Trick.query.filter(Trick.slug == trick_slug).first()
    variant = TrickVariant.query.filter(TrickVariant.slug == variant_slug).first()
    trick_to_delete = UsersTricks.query.filter(UsersTricks.trick_id == trick.id,
                                               UsersTricks.trick_variant_id == variant.id,
                                               UsersTricks.user_id == current_user.id).first()
    variant_count = len(UsersTricks.query.filter(UsersTricks.trick_id == trick.id,
                                                 UsersTricks.user_id == current_user.id).all())
    subtract_points(variant_count, trick.value)
    db.session.delete(trick_to_delete)
    db.session.commit()
    return redirect(url_for('views.profile'))


@views.route('/admin-console')
@login_required
@roles_required('admin')
def admin_console():
    return render_template("admin/admin_console.html", user=current_user)



@views.route('<category>/<slug>')
def show_post(slug, category):
    post_category = Category.query.filter(Category.name == category).first_or_404()
    post = Post.query.filter(Post.slug == slug).first_or_404()
    posts = Post.query.filter(Post.category_id == post_category.id).all()
    if post.media:
        return render_template('posts/post.html', post=post, posts=posts,
                               user=current_user, category=post_category.name)
    else:
        return render_template('posts/post_no_image.html', post=post, posts=posts,
                               user=current_user, category=post_category.name)



@views.route('/all-posts')
@login_required
@roles_required('admin')
def show_all_posts():
    posts = Post.query.all()
    return render_template('posts/show_posts.html', posts=posts, user=current_user)


@views.route('/create-post', methods=['GET', 'POST'])
@login_required
@roles_required('admin')
def create_post():
    categories = Category.query.all()
    if request.method == 'POST':
        title = request.form.get("title")
        content = request.form.get("content")
        file = request.files['file']
        category = request.form.get("category")

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;600;700&display=swap" rel="stylesheet">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='/img/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='/img/favicon-16x16.png') }}">
    <script src="https://kit.fontawesome.com/eb6e6a7399.js" crossorigin="anonymous"></script>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://unpkg.com/scrollreveal@3.3.2/dist/scrollreveal.min.js"></script>


    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark my-nav" role="navigation">
        <div class="container-fluid">
            <a href="{{ url_for('views.home') }}">
                <img src="{{ url_for('static', filename='/img/the-impossible.png') }}" alt="The impossible">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse flex-row-reverse" id="navbarSupportedContent">
                <div class="navbar-nav my-2 my-lg-0">
                    <a class="nav-item nav-link"
                       href="{{ url_for('views.show_post', slug=menu_trick_post.slug, category=menu_trick_category.name) }}">O
                        TRICKACH</a>
                    <a class="nav-item nav-link"
                       href="{{ url_for('views.show_post', slug=menu_about_post.slug, category=menu_about_category.name) }}">O
                        STRONIE</a>
                    <a class="nav-item nav-link" href="{{ url_for('views.dictionary') }}">SŁOWNICZEK</a>
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="/profile">PROFIL</a>
                        <a class="nav-item nav-link" href="/logout">WYLOGUJ SIĘ</a>
                        {% if user.has_role('admin') %}
                            <a class="nav-item nav-link" href="/admin-console">
                                <i class="fa-sharp fa-solid fa-gears"></i>
                            </a>
                        {% endif %}
                    {% else %}
                        <a class="nav-item nav-link" href="/login">ZALOGUJ SIĘ</a>
                        <a class="nav-item nav-link" href="/sign-up">ZAREJESTRUJ SIĘ</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>

{% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                </div>
            {% elif category == 'success' %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endwith %}

<main>
    {% block content %}{% endblock %}
</main>

<footer>
    <a href="{{ url_for('views.show_post', slug=menu_about_post.slug, category=menu_about_category.name) }}"
       class="footer-item">O STRONIE</a>
    <p class="footer-item"> AUTOR: MAREK BORKOWSKI</p>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"
></script>
<script src="{{ url_for('static', filename='js/app.js') }}"></script>

</body>
</html>

website/templates/home.html
{% extends "base.html" %}
{% block title %}Strona główna{% endblock %}
{% block content %}
    <video class="videoBackground" autoplay muted loop>
        <source src="{{ url_for('static', filename="background.mp4") }}" type="video/mp4">
    </video>
    <div class="viewport-header">
        <h1>
            RODNEY MULLEN&nbsp;
        </h1>
        <p>I&nbsp;JEGO NAJPOPULARNIEJSZE TRICKI NA&nbsp;DESKOROLKĘ</p>
    </div>
    <div class="container-fluid">
        <div class="row d-flex justify-content-center">
            <div class="col-10 d-flex flex-column flex-xxl-row flex-xl-row flex-lg-row justify-content-evenly align-items-center">
                <div class="nav-hero" id="tricks">
                    <p class="main-link">
                        O TRICKACH
                    </p>
                    <p>Poznaj tricki Rodney'a Mullena</p>
                    <a href="{{ url_for('views.show_post', slug=menu_trick_post.slug, category=menu_trick_category.name) }}">
                        <svg data-name="Warstwa 1" xmlns="http://www.w3.org/2000/svg"
                             viewBox="0 0 283.46 283.46">
                            <circle class="cls-1" cx="141.73" cy="141.73" r="141.73"></circle>
                            <polygon class="cls-2"
                                     points="126.28 78.06 164.88 117.4 31.78 116.13 31.34 161.82 164.45 163.09 125.11 201.68 157.11 234.3 252.12 141.07 158.9 46.06 126.28 78.06"></polygon>
                        </svg>
                    </a>
                </div>
                <div class="nav-hero" id="about">
                    <p class="main-link">
                        O STRONIE
                    </p>
                    <p>Tutaj znajdziesz informacje o serwisie</p>
                    <a href="{{ url_for('views.show_post', slug=menu_about_post.slug, category=menu_about_category.name) }}">
                        <svg data-name="Warstwa 1" xmlns="http://www.w3.org/2000/svg"
                             viewBox="0 0 283.46 283.46">
                            <circle class="cls-1" cx="141.73" cy="141.73" r="141.73"></circle>
                            <polygon class="cls-2"
                                     points="126.28 78.06 164.88 117.4 31.78 116.13 31.34 161.82 164.45 163.09 125.11 201.68 157.11 234.3 252.12 141.07 158.9 46.06 126.28 78.06"></polygon>
                        </svg>
                    </a>
                </div>
                <div class="nav-hero" id="dict">
                    <p class="main-link">
                        SŁOWNICZEK
                    </p>
                    <p>Zajrzyj tutaj, jeśli czegoś nie rozumiesz</p>
                    <a href="{{ url_for('views.dictionary') }}">
                        <svg data-name="Warstwa 1" xmlns="http://www.w3.org/2000/svg"
                             viewBox="0 0 283.46 283.46">
                            <circle class="cls-1" cx="141.73" cy="141.73" r="141.73"></circle>
                            <polygon class="cls-2"
                                     points="126.28 78.06 164.88 117.4 31.78 116.13 31.34 161.82 164.45 163.09 125.11 201.68 157.11 234.3 252.12 141.07 158.9 46.06 126.28 78.06"></polygon>
                        </svg>
                    </a>
                </div>
            </div>

            <section class="col-10 col-xxl-8">
                <h2>Kim jest Rodney Mullen?</h2>
                <div class="post p-home">
                    <div class="post-media">
                        <img src="{{ url_for('static', filename='/img/814px-Rodney_Mullen_PopTech_2013_01_(cropped).jpg') }}"
                             class="img-fluid"
                             alt="Rodney Mullen">
                    </div>
                    <section class="post-content">
                        <h3>Kariera sportowa</h3>
                        <p>Rodney Mullen zdobył swoje pierwsze mistrzostwo świata w deskorolce w wieku 14 lat; w ciągu
                            następnej dekady wygrał 34 z 35 zawodów freestyle'owych, ustanawiając tym samym najbardziej
                            udaną serię rywalizacji w historii tego sportu. W kolejnych latach odszedł od freestyle'u,
                            przekładając swoje zgromadzone umiejętności na nowszą, inną formę skateboardingu. Jest
                            powszechnie uważany za najbardziej wpływowego street-skatera w historii tego sportu, który
                            wynalazł wiele - jeśli nie większość - trików używanych obecnie, w tym street Ollie,
                            kick-flip, 360-flip, Impossible itp. W konsekwencji Rodney został uznany za "ojca
                            chrzestnego współczesnego street skatingu" w serii gier wideo Tony Hawk, w której jego
                            postać pojawiała się przez około 8 lat.</p>
                        <h3>Publikacje</h3>
                        <p>W 2004 roku wydawnictwo Regan Books opublikowało jego autobiografię, napisaną wspólnie z
                            Seanem Mortimerem. W wydaniu z grudnia 2006 r. Los Angeles Magazine umieścił go wśród 100
                            najbardziej wpływowych osób. W 2011 roku Cole Louison napisał The Impossible, książkę o
                            deskorolce jako całości, w dużej mierze z perspektywy wpływu Mullena. W 2013 roku Rodney
                            został wprowadzony do Skateboarding Hall of Fame a jego deskorolka jest jednym z eksponatów
                            w Narodowym Muzeum Historii Amerykańskiej w Waszyngtonie. Wystąpił również w uznanym filmie
                            dokumentalnym Bones Brigade, An Autobiography.</p>
                        <h3>Poza skateboardingiem</h3>
                        <p>Mullen studiował matematykę i inżynierię na Uniwersytecie Florydy, zanim został
                            współzałożycielem World Industries, największej firmy deskorolkowej w latach 90-tych, która
                            ostatecznie została przejęta przez Globe Shoes, notowaną na giełdzie ASX. Nadal jeździ na
                            deskorolce. Jego doświadczenie w skateboardingu w połączeniu z bardziej analitycznymi
                            zainteresowaniami otworzyło mu drzwi do publikacji 5 patentów na decki i trucki do
                            deskorolki. Rodney jest częścią społeczności TED - wygłosił przemówienia na dwóch TEDx, a
                            także na innych podobnych, często technologicznych, forach, takich jak PopTech, Foo Camp
                            itp.</p>
                    </section>
                </div>
            </section>
        </div>
    </div>
{% endblock %}

website/templates/index.html
{% extends "base.html" %}
{% block title %}Hello{% endblock %}
{% block content %}
    <div class="container">
        <h1>Home Page</h1>
    </div>
{% endblock %}

website/templates/intro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="https://kit.fontawesome.com/eb6e6a7399.js" crossorigin="anonymous"></script>
    <title>The impossible</title>
</head>
<body>

<video class="videoBackground" autoplay muted loop>
    <source src="{{ url_for('static', filename="background.mp4") }}" type="video/mp4">
</video>
<header class="viewport-header">
    <h1>
        THE&nbsp;IMPOSSIBLE
    </h1>
    <p>RODNEY MULLEN&nbsp;I&nbsp;TRICKI NA&nbsp;DESKOROLKĘ</p>
    <a class="hello-link" href="{{ url_for('views.show_post', slug=menu_trick_post.slug, category=menu_trick_category.name) }}">Przejdź dalej >></a>
</header>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"
></script>
<script src="{{ url_for('static', filename='js/app.js') }}"></script>
</body>
</html>

website/templates/login.html
{% extends "base.html" %}
{% block title %}Logowanie{% endblock %}
{% block content %}
    <div class="container">
        <div class="login-form">
            <form method="POST" class="col-10 col-lg-6">
                <h1>
                    ZALOGUJ SIĘ
                </h1>
                <p>Nie masz konta? <a href="/sign-up">Zarejestruj się</a></p>
                <label for="email">Adres E-mail</label>
                <input type="text" id="email" name="email" placeholder="Wpisz adres e-mail">
                <label for="password">Hasło</label>
                <input type="password" id="password" name="password" placeholder="Wpisz hasło">
                <button type="submit">DALEJ >></button>
            </form>
            <div class="col-6 login-info">

            </div>
        </div>
    </div>
{% endblock %}

website/templates/my_tricks.html
{% extends "base.html" %}
{% block title %}My tricks{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <a class="go-back-sm" href="{{ url_for('views.profile') }}">WRÓĆ DO PROFILU</a>
            <div class="accordion side-nav-mobile" id="accordionExample">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            POZOSTAŁE TRICKI
                        </button>
                    </h2>
                    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne"
                         data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <ul class="nav flex-column">
                                {% for link in tricks %}
                                    {% if trick.name == link.name %}
                                        <li class="nav-item side-nav-item active">
                                            <a href="{{ url_for('views.my_trick', trick_slug=link.slug) }}">
                                                {{ link.name|upper }}
                                            </a>
                                        </li>
                                    {% else %}
                                        <li class="nav-item side-nav-item">
                                            <a href="{{ url_for('views.my_trick', trick_slug=link.slug) }}">
                                                {{ link.name|upper }}
                                            </a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-1 col-lg-1 col-xl-2">

                <ul class="nav flex-column side-nav" role="navigation">
                    <a class="go-back" href="{{ url_for('views.profile') }}">WRÓĆ DO PROFILU</a>
                    {% for link in tricks %}
                        {% if trick.name == link.name %}
                            <li class="nav-item side-nav-item active">
                                <a href="{{ url_for('views.my_trick', trick_slug=link.slug) }}">
                                    {{ link.name|upper }}
                                </a>
                            </li>
                        {% else %}
                            <li class="nav-item side-nav-item">
                                <a href="{{ url_for('views.my_trick', trick_slug=link.slug) }}">
                                    {{ link.name|upper }}
                                </a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>

            <div class="col-10">
                <div class="row">
                    <div class="col-lg-8 col-xl-6 order-1">
                        <div class="title">
                            <h1>{{ trick.name|upper }}</h1>
                            <div class="d-flex flex-column flex-lg-row">
                                {% if article == True %}
                                <a class="pe-3" href="{{ url_for('views.show_post', category='tricki', slug=trick.slug) }}">Przejdź do opisu</a>
                                {% endif %}
                                {% if trick.tutorial_link %}
                                <a href="{{ trick.tutorial_link }}">Poradnik w języku angielskim</a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="variant-list">
                            {% for variant in all_variants %}
                                {% if variant.id in user_variants %}
                                    <div class="vl-btns">
                                        <p class="archived">
                                            {{ variant.name|upper }}
                                        </p>
                                        <a class="nav-link"
                                           href="{{ url_for('views.user_edit_trick', trick_slug=trick.slug, variant_slug=variant.slug) }}">
                                            Edytuj Trick
                                        </a>
                                        <form method="POST"
                                              action="{{ url_for('views.delete_user_trick', trick_slug=trick.slug, variant_slug=variant.slug) }}">
                                            <input type="submit" class="nav-link" value="Usuń"
                                                   onclick="return confirm('Are you sure you want to delete this entry?')">
                                        </form>
                                    </div>

                                {% else %}
                                    <div class="vl-btns">
                                        <p>
                                            {{ variant.name|upper }}
                                        </p>
                                        <a class="nav-link"
                                           href="{{ url_for('views.add_trick', trick_slug=trick.slug, variant_slug=variant.slug) }}">
                                            Dodaj Trick
                                        </a>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>

                    <div class="col-lg-4 col-xl-5 order-2 profile-sidebar">
                        <div class="d-none d-lg-flex sidebar-item">
                            <h3>JAK TO DZIAŁA?</h3>
                            <p>Dodawaj tricki, które udało ci się wykonać i zdobywaj punkty.</p><br>
                            <p>Ilość przyznawanych punktów różni się w zależności od poziomu trudności.</p><br>
                            <p>Zdobądź więcej punktów ucząc się różnych wariantów!</p>
                        </div>
                        <div class="sidebar-item">
                            <h3>SŁOWNICZEK</h3>
                            <p>Zajrzyj do słowniczka, jeśli czegoś nie rozumiesz — możliwe,
                                że znajdziesz tam przydatne informacje.</p>
                            <a href="{{ url_for('views.dictionary') }}">Przejdź do słowniczka >></a>
                        </div>
                        <div class="d-none d-lg-flex sidebar-item">
                            <h3>CHCESZ WIEDZIEĆ WIĘCEJ?</h3>
                            <p>Rzuć okiem na ciekawe treści i zaspokój głód wiedzy.</p>
                            <a href="{{ url_for('views.learn_more') }}">Więcej treści >></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}